/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import core.Definitions;
import core.ServerRoomChat;
import core.UserChat;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Estevan
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    public void createUser(String name)
    {
        Definitions.serverIp = fieldIp.getText();
        UserChat user = null;
        try {
            user = new UserChat(name);
        } catch (RemoteException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        User.main(user);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonUser = new javax.swing.JButton();
        buttonServer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldIp = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldNick = new javax.swing.JTextField();
        buttonUser1 = new javax.swing.JButton();
        buttonUser2 = new javax.swing.JButton();
        buttonUser3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("!");
        setMinimumSize(new java.awt.Dimension(160, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        buttonUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonUser.setText("User");
        buttonUser.setToolTipText("");
        buttonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUserActionPerformed(evt);
            }
        });
        getContentPane().add(buttonUser);
        buttonUser.setBounds(10, 220, 120, 30);

        buttonServer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonServer.setText("Server");
        buttonServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonServerActionPerformed(evt);
            }
        });
        getContentPane().add(buttonServer);
        buttonServer.setBounds(10, 39, 120, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Start as:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 120, 17);

        fieldIp.setText("localhost");
        getContentPane().add(fieldIp);
        fieldIp.setBounds(10, 120, 120, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 80, 120, 10);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Server IP:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 100, 90, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Username:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 160, 90, 17);

        fieldNick.setText("Nick");
        getContentPane().add(fieldNick);
        fieldNick.setBounds(10, 180, 120, 30);

        buttonUser1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonUser1.setText("3");
        buttonUser1.setToolTipText("");
        buttonUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUser1ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonUser1);
        buttonUser1.setBounds(90, 250, 41, 30);

        buttonUser2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonUser2.setText("1");
        buttonUser2.setToolTipText("");
        buttonUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUser2ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonUser2);
        buttonUser2.setBounds(10, 250, 41, 30);

        buttonUser3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonUser3.setText("2");
        buttonUser3.setToolTipText("");
        buttonUser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUser3ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonUser3);
        buttonUser3.setBounds(50, 250, 41, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUserActionPerformed
        //createUser(fieldNick.getText());
        //createUser("Steve");
        createUser("Vicky");
        createUser("Jacky");
        dispose();
    }//GEN-LAST:event_buttonUserActionPerformed

    private void buttonServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonServerActionPerformed
        ServerRoomChat server = null;
        try {
            server = new ServerRoomChat();
        } catch (RemoteException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        Server.main(server);
        dispose();
    }//GEN-LAST:event_buttonServerActionPerformed

    private void buttonUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUser1ActionPerformed
        createUser("Steve");
        dispose();
    }//GEN-LAST:event_buttonUser1ActionPerformed

    private void buttonUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUser2ActionPerformed
        createUser("Jacky");
        dispose();
    }//GEN-LAST:event_buttonUser2ActionPerformed

    private void buttonUser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUser3ActionPerformed
        createUser("Vicky");
        dispose();
    }//GEN-LAST:event_buttonUser3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonServer;
    private javax.swing.JButton buttonUser;
    private javax.swing.JButton buttonUser1;
    private javax.swing.JButton buttonUser2;
    private javax.swing.JButton buttonUser3;
    private javax.swing.JTextField fieldIp;
    private javax.swing.JTextField fieldNick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
