package frames;

import core.UserChat;
import interfaces.IRoomChat;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Estevan
 */
public class Room extends javax.swing.JFrame {

    IRoomChat room;
    UserChat user;
    
    public Room(IRoomChat room, UserChat user) throws RemoteException {
        initComponents();
        this.room = room;
        this.user = user;
        labelRoom.setText(room.getName());
        labelUser.setText("User: " + user.usrName);
        user.areaChat = areaChat;
        //refreshUserList();
    }

    public void refreshUserList()
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRoom = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUsers = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaChat = new javax.swing.JTextArea();
        fieldMsg = new javax.swing.JTextField();
        labelUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Room");
        setMinimumSize(new java.awt.Dimension(290, 360));
        getContentPane().setLayout(null);

        labelRoom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelRoom.setText("Room name");
        getContentPane().add(labelRoom);
        labelRoom.setBounds(10, 11, 160, 22);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 44, 250, 10);

        listUsers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listUsers);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(182, 83, 75, 191);

        areaChat.setEditable(false);
        areaChat.setColumns(20);
        areaChat.setRows(5);
        jScrollPane2.setViewportView(areaChat);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 83, 166, 191);

        fieldMsg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldMsgKeyPressed(evt);
            }
        });
        getContentPane().add(fieldMsg);
        fieldMsg.setBounds(10, 280, 166, 30);

        labelUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUser.setText("User: Steve");
        getContentPane().add(labelUser);
        labelUser.setBounds(121, 10, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Users");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(182, 60, 33, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Chat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 60, 29, 17);

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonExit);
        buttonExit.setBounds(180, 280, 80, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonExitActionPerformed

    private void fieldMsgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldMsgKeyPressed
        if (evt.getKeyCode() == 10) // Enter.
        {
            try {
                room.sendMsg(user.getName(), fieldMsg.getText());
                fieldMsg.setText("");
            } catch (RemoteException ex) {
                Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_fieldMsgKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(IRoomChat room, UserChat user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Room(room, user).setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaChat;
    private javax.swing.JButton buttonExit;
    private javax.swing.JTextField fieldMsg;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelRoom;
    private javax.swing.JLabel labelUser;
    private javax.swing.JList<String> listUsers;
    // End of variables declaration//GEN-END:variables
}
