package frames;

import core.UserChat;
import interfaces.IRoomChat;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Estevan
 */
public class Room extends javax.swing.JFrame {

    IRoomChat room;
    UserChat user;
    
    public Room(IRoomChat room, UserChat user) throws RemoteException {
        initComponents();
        this.room = room;
        this.user = user;
        labelRoom.setText(room.getName());
        labelUser.setText("User: " + user.usrName);
        user.areaChat = areaChat;
        buttonSend.setEnabled(false);
    }

    public void sendMessage()
    {
        try {
            room.sendMsg(user.usrName, fieldMsg.getText());
        } catch (RemoteException ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }
        fieldMsg.setText("");
        buttonSend.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRoom = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaChat = new javax.swing.JTextArea();
        fieldMsg = new javax.swing.JTextField();
        labelUser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonSend = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Room");
        setMinimumSize(new java.awt.Dimension(290, 400));
        getContentPane().setLayout(null);

        labelRoom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelRoom.setText("Room");
        getContentPane().add(labelRoom);
        labelRoom.setBounds(10, 11, 160, 22);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 44, 250, 10);

        areaChat.setEditable(false);
        areaChat.setColumns(20);
        areaChat.setRows(5);
        jScrollPane2.setViewportView(areaChat);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 83, 250, 191);

        fieldMsg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldMsgKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldMsgKeyReleased(evt);
            }
        });
        getContentPane().add(fieldMsg);
        fieldMsg.setBounds(10, 280, 250, 30);

        labelUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUser.setText("User: Steve");
        getContentPane().add(labelUser);
        labelUser.setBounds(121, 10, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Chat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 60, 29, 17);

        buttonSend.setText("Send");
        buttonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSend);
        buttonSend.setBounds(10, 320, 120, 30);

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonExit);
        buttonExit.setBounds(150, 320, 110, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendActionPerformed
        sendMessage();
    }//GEN-LAST:event_buttonSendActionPerformed

    private void fieldMsgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldMsgKeyPressed
        if (evt.getKeyCode() == 10) // Enter.
            sendMessage();
    }//GEN-LAST:event_fieldMsgKeyPressed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        try {
            room.leaveRoom(user.usrName);
        } catch (RemoteException ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }
        User.main(user);
        dispose();
    }//GEN-LAST:event_buttonExitActionPerformed

    private void fieldMsgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldMsgKeyReleased
        buttonSend.setEnabled(fieldMsg.getText().length() > 0);
    }//GEN-LAST:event_fieldMsgKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(IRoomChat room, UserChat user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Room(room, user).setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaChat;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonSend;
    private javax.swing.JTextField fieldMsg;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelRoom;
    private javax.swing.JLabel labelUser;
    // End of variables declaration//GEN-END:variables
}
